Gnome: Add renamed option module for favoriteAppsOverride
Getting the following error when switching from 25.05 to unstable
`` 
error: The option `services.xserver.desktopManager.gnome.favoriteAppsOverride' does not exist.
``

Seems that a rename was missing for this option